-- V1__initial_schema.sql
-- Initial database schema for Ergonomics Monitor
-- Creating tables for activity events, break recommendations and dashboard metrics

-- Extension for UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Activity Events table - main event storage
CREATE TABLE IF NOT EXISTS activity_events (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    type VARCHAR(50) NOT NULL,
    intensity DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    metadata JSONB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_activity_events_user_id ON activity_events(user_id);
CREATE INDEX IF NOT EXISTS idx_activity_events_timestamp ON activity_events(timestamp);
CREATE INDEX IF NOT EXISTS idx_activity_events_type ON activity_events(type);
CREATE INDEX IF NOT EXISTS idx_activity_events_user_timestamp ON activity_events(user_id, timestamp DESC);

-- GIN index for JSONB metadata queries
CREATE INDEX IF NOT EXISTS idx_activity_events_metadata ON activity_events USING GIN(metadata);

-- Break Recommendations table - AI-generated recommendations history
CREATE TABLE IF NOT EXISTS break_recommendations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL,
    urgency VARCHAR(20) NOT NULL,
    duration_minutes INTEGER NOT NULL,
    reason TEXT NOT NULL,
    ai_generated BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    accepted_at TIMESTAMP WITH TIME ZONE,
    dismissed_at TIMESTAMP WITH TIME ZONE,
    metadata JSONB
);

-- Indexes for break recommendations
CREATE INDEX IF NOT EXISTS idx_break_recommendations_user_id ON break_recommendations(user_id);
CREATE INDEX IF NOT EXISTS idx_break_recommendations_created_at ON break_recommendations(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_break_recommendations_urgency ON break_recommendations(urgency);

-- Dashboard Metrics table - pre-aggregated statistics for performance
CREATE TABLE IF NOT EXISTS dashboard_metrics (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL,
    metric_date DATE NOT NULL,
    total_events BIGINT NOT NULL DEFAULT 0,
    avg_intensity DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    max_intensity DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    break_recommendations_count INTEGER NOT NULL DEFAULT 0,
    work_duration_minutes INTEGER NOT NULL DEFAULT 0,
    break_duration_minutes INTEGER NOT NULL DEFAULT 0,
    productivity_score DOUBLE PRECISION,
    metadata JSONB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    -- Unique constraint for one metric per user per day
    UNIQUE(user_id, metric_date)
);

-- Indexes for dashboard metrics
CREATE INDEX IF NOT EXISTS idx_dashboard_metrics_user_date ON dashboard_metrics(user_id, metric_date DESC);
CREATE INDEX IF NOT EXISTS idx_dashboard_metrics_date ON dashboard_metrics(metric_date);

-- Trigger function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Triggers for updating timestamps
CREATE TRIGGER update_activity_events_updated_at
    BEFORE UPDATE ON activity_events
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_dashboard_metrics_updated_at
    BEFORE UPDATE ON dashboard_metrics
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Comments for documentation
COMMENT ON TABLE activity_events IS 'Stores all user activity events with metadata';
COMMENT ON TABLE break_recommendations IS 'AI-generated and system break recommendations history';
COMMENT ON TABLE dashboard_metrics IS 'Pre-aggregated daily metrics for dashboard performance';

COMMENT ON COLUMN activity_events.intensity IS 'Activity intensity score (0.0 - 1000.0+)';
COMMENT ON COLUMN activity_events.metadata IS 'Additional event data as JSON';
COMMENT ON COLUMN break_recommendations.ai_generated IS 'True if recommendation was generated by AI';
COMMENT ON COLUMN dashboard_metrics.productivity_score IS 'Calculated productivity score (0.0 - 100.0)';
